server:
  port: 9503

spring:
  application:
    name: withdrawl-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: amount-withdrawl-event
      isolation-level: read_committed