server:
  port: 9501

spring:
  application:
    name: deposit-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: amount-deposit-event
      isolation-level: read_committed
